from cryptography.hazmat.primitives import hashes
from sympy import sieve
import random
import math
import binascii

#=====================================================
# Please do NOT modify the following code, but you are more than welcome to understand the code in detail

# Define a hash function class for Task C.
# The method get_hash_value(message) function return a hash value raning in [0, 365)
class HashFunctionTaskC:
    
    upper_bound = 1
    
    def __init__(self, upper_bound):
        self.upper_bound = upper_bound
    
    def get_hash_value(self, message = None):
        if(None==message):
            sys.exit("No message is given!")
            
        # Padding empty string
        if(len(message) == 0):
            message = "0"
        
        hash_value = ord(message[0])
    
        # The hash value is generated by taking the product (modulo 365) of the ordinal numbers of characters at the positions indexed by prime numbers
        for i in sieve.primerange(len(message)):
            hash_value = (ord(message[i-1])*hash_value)%self.upper_bound
    
        return hash_value


# Implement the birthday attack for a hash function
def birthday_attack(message_space, hash_function):
    
    has_collision = False
    tried_hash_values = set()
    collision_pair_1 = -1
    collision_pair_2 = -1
    
    random_index_samples = random.sample(range(len(message_space)), len(message_space)); # Random sampling without replacement
    
    for i in range(len(message_space)):   
        hash_value_1 = hash_function.get_hash_value(message_space[random_index_samples[0]])
        tried_hash_values.add(hash_value_1)
        for j in range(1, len(random_index_samples)):
            hash_value_2 = hash_function.get_hash_value(message_space[random_index_samples[j]])
            if hash_value_1 == hash_value_2:
                has_collision = True
                collision_pair_1 = random_index_samples[0]
                collision_pair_2 = random_index_samples[j]
                break
            else:
                tried_hash_values.add(hash_value_2)
                    
        if has_collision:
            break
        random_index_samples = random.sample(random_index_samples[1:], len(random_index_samples[1:]))
    
    if has_collision:
        return len(tried_hash_values), collision_pair_1, collision_pair_2
    else:
        print("No collision is found!")
        return -1, -1, -1    

    
# Examples of using this hash function
hash_function = HashFunctionTaskC(upper_bound=365)

example_message = "Hellow World, COMP2300/6300!"
print("Example message is: ", example_message)
print("Hash value of example message is: ", hash_function.get_hash_value(example_message))

modified_example_message = "Hell0w World, COMP2300/6300!"
print("Modified example message is: ", modified_example_message)
print("Hash value of modified example message is: ", hash_function.get_hash_value(modified_example_message))
print("")

# Example of perform birthday attack
# We use each line of the plain text in Task B.2 as a message. Then, the whole text can be regarded as a set of messages.
# Note that you need to replace the plain text file name (i.e., to replace <YourStudentID> with your own ID) to execute the program correctly
message_list  = None
with open(r"C:\Users\abhay\Desktop\Uni\Year 2\semester 2\comp2300\Assignment 1\47717653_Task-B-2_plain-text.txt", encoding='utf-8') as file:
    message_list = file.read().splitlines()

# Show the number of messages
print("Number of messages: ", len(message_list))

# Perform the birthday_attack to the hash function once. The upper bound of hash values are set as 365.
count, cp1, cp2 = birthday_attack(message_list, HashFunctionTaskC(upper_bound=365))
print("The number of examined hash values (NOT the number of examined messages) before the first collision: \n%i" %count)
print("Collided message 1: ", cp1)
print(message_list[cp1])
print("Collided message 2: ", cp2)
print(message_list[cp2])
print("")


#=====================================================
# Following area is for your to write or complete the code to achieve the answers to Task C

# Subtask C.1 (2 marks): Use the same setting as the example (i.e., the same hash function and the same message set from the same file "<YourStudentID>_Task-B-2_plain-text.txt").
# You are required to perform to the birthday attack multiple times (>=500), and calculate the average number of examined hash values before the first collision.
# Compare the empirical average number of examined hash values before the first collision with its theoretical value (i.e., sqrt(Pi/2*n), where n is the number of possible hash values) to check if the difference is significant.
# Report the following information as the answers to Task C.1 in the answer template:
# (1) the rounds of birthday attacks of your choice, (2) the empirical average number of examined hash values before the first collision, (3) the theoretical value, and (4) the explanation on the difference between the empirical value and the theoretical value.

print("\n--- Subtask C.1 ---")
# TODO: Your code to achieve the subtask above
# Subtask C.1 (2 marks)
num_iterations = 500  
total_count = 0

# Birthday attacks multiple times
for _ in range(num_iterations):
    count, _, _ = birthday_attack(message_list, HashFunctionTaskC(upper_bound=365))
    total_count += count

# Calculate empirical average
empirical_average = total_count / num_iterations

# Calculate theoretical value
n = 365  
theoretical_value = math.sqrt(math.pi / 2 * n)

# Calculate difference
difference = empirical_average - theoretical_value

print("Number of birthday attack iterations:", num_iterations)
print("Empirical average number of examined hash values before the first collision:", empirical_average)
print("Theoretical value:", theoretical_value)
print("Difference:", difference)


# Subtask C.2 (1 mark): Through understanding the construction of the hash function, you are requested to forge a message for a given message, i.e., to identify a second preimage.
# The given message is Line 6 in the file "<YourStudentID>_Task-B-2_plain-text.txt".
# The change should be minor with substitution of a few characters, and the modified version still produces the same hash value as the given message.
# Report (1) the forged message and (2) the explanation why the modification works as the answers to Task C.2 in the answer template.


print("\n--- Subtask C.2 ---")
print("Line 6 message: ", message_list[5])
print("Line 6 message hash value: ", hash_function.get_hash_value(message_list[5]))
print("")

# Get given message 
given_message = message_list[5]

# Find prime number positions within message
prime_positions = list(sieve.primerange(len(given_message) + 1))[1:]  

# Calculate original hash value
original_hash_value = hash_function.get_hash_value(given_message)

# Create list to store modified message
forged_message = list(given_message)

# Limit number of substitutions 
max_substitutions = 3
substitution_count = 0

# Modify characters at non-prime positions keeping hash value same
for i in range(len(given_message)):
    if i not in prime_positions and substitution_count < max_substitutions:
        original_ordinal = ord(given_message[i])
        
        # Try different offsets until different character is found with same hash value
        offset = 1
        while offset < 365:
            new_ordinal = (original_ordinal + offset) % 365
            if new_ordinal != original_ordinal:
                forged_message[i] = chr(new_ordinal)
                new_hash_value = hash_function.get_hash_value("".join(forged_message))
                if new_hash_value == original_hash_value:
                    substitution_count += 1
                    break  
                else:
                    forged_message[i] = given_message[i]  
            offset += 1

# Convert the modified message list back to string
forged_message = "".join(forged_message)

# Print the forged message hash value
print("Forged message: ", forged_message)
print("Forged message hash value: ", hash_function.get_hash_value(forged_message))


# Subtask C.3 (2 marks): Now, you are requested to employ MD5 to generate the hash values for the Line 6 message and the forged message (the same as in Task C.2)
# How to use MD5 to generate hash values can be found here: https://cryptography.io/en/latest/hazmat/primitives/cryptographic-hashes/#cryptography.hazmat.primitives.hashes.MD5.
# Compare the two hash values to see if they are equal to each other
# Report the following information as the answers to Task C.3 in the answer template:
# (1) the hash values of the two messages, (2) the percentage of the overlap between the two hash values at the bit level,
# and (3) which hash function has a stronger avalanche effect, MD5 or the hash function we defined above?

# TODO: Your code to generate hash values and calculate the percentage of the overlap between the two hash values

 #Function to calculate MD5 hash
def get_md5_hash(message):
    digest = hashes.Hash(hashes.MD5())
    digest.update(message.encode('utf-8'))
    return digest.finalize()

original_message = message_list[5]

# Calculate MD5 hashes
original_hash_md5 = get_md5_hash(original_message)
forged_hash_md5 = get_md5_hash(forged_message)

# Convert hashes to binary strings for bit-level comparison
original_hash_bits = bin(int.from_bytes(original_hash_md5, byteorder='big'))[2:].zfill(128)  
forged_hash_bits = bin(int.from_bytes(forged_hash_md5, byteorder='big'))[2:].zfill(128)

# Calculate overlap percent
matching_bits = sum(1 for i in range(128) if original_hash_bits[i] == forged_hash_bits[i])
overlap_percentage = (matching_bits / 128) * 100

# Print results
print("\n--- Subtask C.3 ---")
print("Original message MD5 hash:", original_hash_md5.hex())
print("Forged message MD5 hash:", forged_hash_md5.hex())
print("Overlap percentage at bit level:", overlap_percentage)

# Compare avalanche effect
if overlap_percentage < 50:  
    print("MD5 has a stronger avalanche effect.")
else:
    print("The custom hash function has a stronger avalanche effect.") 